support for dynamic batch sizes at runtime
worldcoin/signup-sequencer pull request #507
Opened 2023-05-09 14:21 UTC by TheMenko

This PR is a follow up to #485

2023-05-10 11:29 UTC, gswirski requested changes
We should think about the migration plan. With this PR, there are two ways to initialize provers: from the ENV var, and from the database. There should be only one source of truth - the database.

Since we don't want to restart our production service unnecessarily (currently it takes minutes), we need to be careful how we proceed with the deployment of this. My suggestion would be:
* Keep the ENV var setting for now. When initializing the identiy_manager, we try to `restore_provers` from the db first. If and only if we get 0 provers, we fetch them from the ENV var (and insert into the db).
* Once all environments have been properly migrated (i.e. they have provers in the database), we remove the ENV var altogether
* To make future deployments and local setup easier, /insertIdentity endpoint should warn that there are no provers available and hint at addProver admin endpoint.

2023-05-10 11:29 UTC, gswirski commented on src/app.rs
> +        // restore prover state from previus shutdown
nit: `previous`

2023-05-10 11:29 UTC, gswirski commented on src/database/mod.rs
> +        tx.execute(query).await?;
nit: do we need an explicit transaction here? wouldn't `self.pool.execute(query)` work the same?

2023-05-11 12:17 UTC, gswirski requested changes
Tagging @cichaczem to confirm that it's OK to allow only one URL per batch size (given he's experimenting with more prover replicas).

I think this PR still doesn't quite work. We have a set of existing provers in the ENV var. We deploy this change, restart the process... and now we still only have those provers in the ENV var. We can't use the API to create those provers in the database because we'll end up adding duplicate batch_sizes to the identity manager.

IMHO we should do it such that if we read prover configuration from the ENV var, we migrate it to the db right away. The next time sequencer starts, the ENV is no longer used. Does it makes sense to you, @cichaczem ? I'm assuming the next PR would completely remove dependence on ENV var once all sequencer instances have been updated with this.

2023-05-11 12:17 UTC, gswirski commented on src/database/mod.rs
> +    pub async fn write_prover(
nit: `insert_prover` or even `insert_prover_configuration` to be more consistent with other db methods

2023-05-11 12:17 UTC, gswirski commented on src/database/prover.rs
> +pub struct Prover {
nit: maybe `ProverConfiguration` for clarity?

2023-05-12 08:37 UTC, cichaczem commented
Regarding `only one URL per batch size`. We should deploy additional instances using the infra setup if we want multiple provers for the same batch size. K8s can manage deployment and load balancing for us using 1-2 settings in the deployment description. In that manner, we should have only one URL per batch size.

2023-05-12 08:39 UTC, cichaczem commented
Ditto on @gswirski comment about populating DB with the list of provers in the ENV. Let's deploy that first, make sure we have every prover in, and remove the ENV in a separate PR.

2023-05-15 20:40 UTC, gswirski approved these changes

2023-05-15 20:41 UTC, merged